### ISSUE TITLE
Creator Contract

### ISSUE THREAD

**Issue by DanM3rcurius** [SoU-DisCo-of-Urgency/Documentation#10]
## Goal
Have a contract template ready for Tea & Pedro

## To Do's

- [x] Create Draft
- [x] Review with Heather (asynchronous) 
- [x] Final Draft

### Current Draft
[Contract freelancer gGmbH_template.pdf](https://github.com/SecretDecks/Artist-Coordination/files/7500797/Contract.freelancer.gGmbH_template.pdf)

**Comment by evolayak** [comment]
Looks good to me, @DanM3rcurius ! I would just change the address at the top to SoU info- will post to both Discord and Telegram to get the info. Sorry, I didn't do that before sending it to you.
