### ISSUE TITLE
2021-10-26: FTR NFT Ticket call with Pedro Marum

### ISSUE THREAD

**Issue by evolayak** [SoU-DisCo-of-Urgency/Documentation#7]
## Attendees: Dan, Heather, Pedro Marum
- Heather gave the backstory of why we initiated call, a bit about how she and Dan are involved with DoU, very briefly how DoU came about but barely scratched the surface.
- After this, Pedro read through the 1-pager and shared that he's super busy and the deadline proposed was too tight.
- Heather said this could be worked around, that at this point we just needed to know if he would like to join forces and move forward. Then we can work around his schedule for "delivery" of his artistic contribution (performance date, release of special access to music, etc.)
- Pedro initially expressed concern about his art being ephemeral and not physical artefacts; also concerned about who would want to consumed this kind of art.
- Dan jumped on the call at just the right moment and explained why an ephemeral artistic experience is indeed appealing, not at all limiting, and indeed constitutes an artefact (also why an NFT/NFT incentive format for this is great); how the incentives (and NFTs) can take on just about any form; we're not limited, and the deadlines for Pedro are a bit flexible.
- Pedro asked about who would be interested in buying an NFT with his art as an incentive.
- Dan explained very succinctly why the Cardano Community would be down for buying something like this, that it's supporting a cause, wanting to put trust in a project, how the community values social impact projects.
- Pedro asked what kind of obligations aside from his art would be needed.
- Dan answered "nothing" and that we would include a disclaimer that this is an experiment, not a guarantee that the buyers will receive XYZ. (Meanwhile, Heather is thinking "bravo" because this would also be her concern as a busy artist.)
- Pedro requested a week or so to think things over.
- Dan, Heather and Pedro will convene again in one week to discuss if Pedro wants to contribute. 
- In the meantime, Heather will work on a two ticket versions, one tied to the artistic incentives provided by Pedro and one in case he decides not to join in.

**Comment by DanM3rcurius** [comment]
looks good, I'll close it as the meeting has concluded and we had the next one!
